#TUTORIAL ISENSORS
#Using Test dataset for hypocotyle

#........iSensors Instalation
# Make sure you have devtools installed
BiocManager::install("universalmotif")
install.packages("devtools")

# Install the iSensor package from main
devtools::install_github("MironovaLab/iSensors")
# or from other branch
devtools::install_github("MironovaLab/iSensors", ref = "iSensors-v1.2.0-dev")
pak::pak("MironovaLab/iSensors")

#........Tutorial
# Load the package
library(iSensors)

# Check installed version
packageVersion("iSensors")

# Access general help page for more information about the package and its functions
help("iSensors")

#Load the required libraries 
library(Seurat)

#Load the test dataset 
testData <- readRDS("testData.rds") #This is a scRNA-seq dataset of Arabidopsis hypocotyl cell types generated by Zhou et al. (2025)

#Visualize and inspect the dataset 
str(testData)
DimPlot(testData, label = TRUE) + NoLegend()

# Load test panel with meta-panels
testPanel <- LoadSensors(setName = 'testPanelSet', species = 'ATH', hormone = 'aux', customPanels = TRUE,
                         randomInfo = list('n' = 3, 'sizes' = c(100, 200, 300), majortrend = TRUE)
                         metaPanels = list(
                           'meta1' = list('srcPanels' = c("ATH-aux-cis-DR5-ARF1", "ATH-aux-reg-DR5-ARF5-2-up"), rule = mean),
                           'meta2' = list('srcPanels' = c("ATH-aux-cis-DR5-ARF1", "ATH-aux-reg-DR5-ARF5-2-up"), rule = prod)
)

# Calculate signaling scores for selected panels

result <- CalcSensors(testData,
                      seurLayer = "RNA",
                      panelSet = testPanel,
                      signals = c("mean_normed", "median"))
result@meta.data #The resulting signaling scores can now be found in the metadata of our Seurat object 'result'

#Visualizing result
DefaultAssay(result) <- 'iSensors_mean_normed'
FeaturePlot(object = result, features = 'AT-aux-trans-EffluxInflux', label = TRUE) #Showing the expression for one of the panels 
VlnPlot(result, features = 'AT-aux-trans-EffluxInflux') + NoLegend()
all_panels <- rownames(result@assays$iSensors_mean_normed)
DoHeatmap(result, features = all_panels, slot = 'counts') #Visualizing the expression of all panels for all clusters
trans_panels <- all_panels[grep("^AT-aux-trans-", all_panels)]
DoHeatmap(result, features = trans_panels, slot = 'counts') #Visualizing the expression of trans panels for all clusters

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#PREPARING THE TEST DATASET
#Link paper: https://www.nature.com/articles/s41467-025-59072-y
#Link data: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE224928 
library(Seurat)

seurat.obj <- readRDS("//mironova.z.science.ru.nl/mironova/scRNA-seq datasets/Zhao et al. 2025 Arabidopsis Hypocotyl/GSE224928_10x_All_hypocotyl.rds")
str(seurat.obj)

DimPlot(seurat.obj, label = TRUE)
seurat.obj <- RenameIdents(seurat.obj,
                           "0"= "Developing phloem",
                           "1"= "Unknown 2",
                           "2"= "Unknown 1",
                           "3"= "Periderm",
                           "4"= "Unknown 3",
                           "5"= "Xylem Parenchyma 1",
                           "6"= "Cambium Stem Cell",
                           "7"= "Unknown 4",
                           "8"= "Epidermis",
                           "9"= "Cortex",
                           "10"= "Cortex-Epidermis",
                           "11"= "Companion Cell",
                           "12"= "Xylem Parenchyma - Developming vessel",
                           "13"= "Xylem Parenchyma 2",
                           "14"= "Phloem Parenchyma",
                           "15"= "Developing Cortex",
                           "16"= "Phellem",
                           "17"= "Dividing Cell") #All double checked from Figure 1 paper
seurat.obj$CellTypes <- Idents(seurat.obj)

saveRDS(seurat.obj, "//mironova.z.science.ru.nl/mironova/Fabienne/iSensor/testData.rds")

seurat.obj.clean <- subset(seurat.obj, idents = c("Unknown 1", "Unknown 2" , "Unknown 3", "Unknown 4"), invert = TRUE)
unique(Idents(seurat.obj.clean))
saveRDS(seurat.obj.clean, "//mironova.z.science.ru.nl/mironova/Fabienne/iSensor/testDataClean.rds")

testPanel <- LoadSensors(
  setName = 'testPanelSet',
  species = 'ATH',
  hormone = 'aux',
  customPanels = TRUE,
  randomInfo = list('n' = 3, 'sizes' = c(100, 200, 300), majortrend = TRUE),
  metaPanels = list(
    'meta1' = list(
      'srcPanels' = c("ATH-aux-cis-DR5-ARF1", "ATH-aux-reg-DR5-ARF5-2-up"),
      rule = function(x) {
        if (length(x) == 0) return(NA_real_)
        mean(x, na.rm = TRUE)
      }
    ),
    'meta2' = list(
      'srcPanels' = c("ATH-aux-cis-DR5-ARF1", "ATH-aux-reg-DR5-ARF5-2-up"),
      rule = function(x) {
        if (length(x) == 0) return(NA_real_)
        prod(x, na.rm = TRUE)
      }
    )
  )
)
